Use `go-git`, configure Bazel
* Add `.bazelversion` and pin Bazel to 8.0.1.
* Use `go-git` instead of relying on `git` being present on the host OS.
* `cloudflare_circl` runs into the following error, so I added a patch:

      $ bazel build //src:cli
      INFO: Analyzed target //src:cli (0 packages loaded, 0 targets configured).
      ERROR: /home/gitpod/.cache/bazel/_bazel_gitpod/1cbf3ee8e72719672606ccd0e3ec481e/external/gazelle++go_deps+com_github_cloudflare_circl/dh/x25519/BUILD.bazel:3:11: GoCompilePkg external/gazelle++go_deps+com_github_cloudflare_circl/dh/x25519/x25519.a failed: (Exit 1): builder failed: error executing GoCompilePkg command (from target @@gazelle++go_deps+com_github_cloudflare_circl//dh/x25519:x25519) bazel-out/k8-opt-exec-ST-d6cc8b84a7bb/bin/external/rules_go++go_sdk+go_default_sdk/builder_reset/builder compilepkg -sdk external/rules_go++go_sdk+go_default_sdk -installsuffix linux_amd64 -src ... (remaining 41 arguments skipped)
      
      Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
      external/gazelle++go_deps+com_github_cloudflare_circl/dh/x25519/curve_amd64.s:7: #include: open external/gazelle++go_deps+com_github_cloudflare_circl/math/fp25519/fp_amd64.h: no such file or directory
      compilepkg: error running subcommand external/rules_go++go_sdk+go_default_sdk/pkg/tool/linux_amd64/asm: exit status 1
      Target //src:cli failed to build
      Use --verbose_failures to see the command lines of failed build steps.
      INFO: Elapsed time: 4.617s, Critical Path: 3.40s
      INFO: 77 processes: 10 internal, 67 linux-sandbox.
      ERROR: Build did NOT complete successfully